### ISSUE TITLE
Failed to create thread

### ISSUE THREAD

**Issue by davidvilanova** [jiwoongbio/FMAP#2]
Hi any idea why it´s not creating the multithreads ??

`echo "perl /home/da/work/FMAP/FMAP_mapping.pl allgenes.fa -p 10 -t tmp > outfile" | qsub -pe parallel_smp 10 -e err -o out`

==> err <==
 [3.08769s]
Building query histograms...  [0.144188s]
Error: Failed to create thread.

**Comment by jiwoongbio** [comment]
Hi,
Can you try "perl /home/da/work/FMAP/FMAP_mapping.pl allgenes.fa -p 1 -t tmp > outfile" first?
