### ISSUE TITLE
Getting error at FMAP_quantification.pl 

### ISSUE THREAD

**Issue by JosephAdelskov** [jiwoongbio/FMAP#5]
Hi there, 
I am testing out your program with a single sample. The FMAP_assembly work flow worked. However I am trying the FMAP_mapping work flow and get an error when parsing the output of FMAP_mapping.pl to FMAP_quantification.pl

$ FMAP_quantification.pl blastx_hits.txt > CS1BS_mapping_abundance.txt

ERROR in /home/joseph/biotools/programs/FMAP-0.10/FMAP_quantification.pl: Use of uninitialized value $percentIdentity in numeric lt (<) at /home/joseph/biotools/programs/FMAP-0.10/FMAP_quantification.pl line 86, <$reader> line 1.

perl version is v5.22.1 on ubuntu server.

First 10 lines of my blastx_hits.txt

M00566:77:000000000-ATBW8:1:2106:7118:2648      K06911_UniRef90_E8YRU9  50.0    70      35      0       211     2       28      97      5.5e-11 70.9
M00566:77:000000000-ATBW8:1:2106:14488:2648     K08641_UniRef90_A0A1D7QDD3      50.7    71      35      0       1       213     158     228     1.1e-17 93.6
M00566:77:000000000-ATBW8:1:2106:9279:2649      K02037_UniRef90_A0A0D5NE94      75.3    97      24      0       291     1       186     282     1.4e-33 146.4
M00566:77:000000000-ATBW8:1:2106:8751:2649      K13688_UniRef90_D3P6W0  51.8    112     40      1       1       294     296     407     5.6e-19 97.8
M00566:77:000000000-ATBW8:1:2106:9476:2650      K00784_UniRef90_D2BNS6  43.5    62      35      0       188     3       8       69      3.8e-07 58.5
M00566:77:000000000-ATBW8:1:2106:16489:2650     K01961_UniRef90_F8I902  76.9    52      12      0       24      179     1       52      2.9e-15 84.7
M00566:77:000000000-ATBW8:1:2106:14734:2650     K02660_UniRef90_K9THH3  41.8    98      55      2       300     10      665     761     1.0e-07 60.5
M00566:77:000000000-ATBW8:1:2106:14734:2650     K02660_UniRef90_K9THH3  37.9    58      33      1       198     25      576     630     5.4e-01 38.1
M00566:77:000000000-ATBW8:1:2106:7969:2650      K03088_UniRef90_C1AB78  57.3    89      38      0       6       272     14      102     5.9e-23 110.9

**Comment by jiwoongbio** [comment]
Hi Joseph,

The input and output table files of FMAP have values separated by "tab". Can you please check if the delimiter of "blastx_hits.txt" is tab or space?
Thanks.

Best Regards,
Jiwoong

**Comment by JosephAdelskov** [comment]
Hi Jiwoong,

The file does appear to be tab delimited. I also tried running the file through awk to replace with tabs but I still get the same error.

**Comment by jiwoongbio** [comment]
The quantification function works well with first 10 lines of your "blastx_hits.txt".
Can you please share the whole file? Do you have a way to share?

**Comment by JosephAdelskov** [comment]
Sorry for the late reply.

I don't have a simple way to send the whole file but I tried running just the sample I had posted which returned the same error.
Could there be perl libraries specific dependency to this script that I am missing?

**Comment by JosephAdelskov** [comment]
I was able to work around the problem by cloning the repository instead of using the release.
Making sure it was directed to the correct version of diamond and run the mapping analysis again.
